### ISSUE TITLE
Cannot resolve library tag in maven repo

### ISSUE THREAD

**Issue by pzienowicz** [jayschwa/AndroidSliderPreference#12]
Hi,

Please create 1.0 tag, because now it is not possible to download the library from the maven.
I know I can specify commit or branch, but we have tags so please use it.

> dependencies {
    // [...]
    compile 'com.github.jayschwa:AndroidSliderPreference:1.0'
}

**Comment by jayschwa** [comment]
[v1.0.0](https://github.com/jayschwa/AndroidSliderPreference/tree/v1.0.0) tag created.
