### ISSUE TITLE
Misleading setup for "Using a Module"

### ISSUE THREAD

**Issue by liquidvapour** [jayschwa/AndroidSliderPreference#8]
Document says that you should clone the repository into your libs folder. This will create a folder called AndroidSliderPreference.

The document goes on to tell you to all the following to your settings.gradle.

`project(':SliderPreference').projectDir = new File('libs/SliderPreference')`

This causes an error during gradle sync as there is no SliderPreference folder.

I propose updating the documentation to: 

`project(':SliderPreference').projectDir = new File('libs/AndroidSliderPreference')`

**Comment by jayschwa** [comment]
Thank you for pointing this out.
